travis:
  secure:
    BINSTAR_TOKEN: ZeVe4Arw6RrUryy4mjou8tJSwPQm//4qy5utZ+cuJ5cvuPZ95UZDayex8nXyoaWKuhSvYlvcZbjFDCS+1J/6k0P5cHA2i2KOW0OUBqJejD77mkBfRT8Vdg2fTef6DPyGPJPzKb9asE3nW/KbGIVg9jZ/9a/E2KgRRm0jEyI9GpbFBKYrhOhvMyULDRRuEh9YVdrbe8DGupApsCORNt2JrevkhW2OkiwdV8UA5XrMCHETZQe9SQFve9THluS0cNzVdUfaIE9TjuXlHeda5/eySDqE81c/qLbcpPfuUe3gt4K7DLWyjI614yGiX5xEHA6boVOFBFIOVjWhzKn+BDKR7JXTsiHPComP7tkb98xbPQbilIjemcWCF+z0/rjas7zR+ATdsmKHgWAyM1VPQYI9etHFWDTl8p/Rarjow0oNgyqJq+wDjEPkrC21DKBx2VKmN/S6oY+3FHTRWDmvLA4aDJe105OiCnTjYVg0Siu2H6N0ogysbSzowF4VqO44bwXGM5LPTnx47ulVpsqjX38gLc7e+gKEHegM18qJi9ezuMQI7UVNqIpBFvoRVtZMRBlCO0XIoQxpm8HXe8GLnD0pp+RbvWbmNqfdGEreTHM4xwpD9bJayBe9jbm9ygy2CLp6mCTcTLiKDaR3N8qsOYDBn95V31mCJkI6D/CS8yKYo5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
